(() => {
  const routes = { 'clase-1': 'clase1.html', 'clase-2': 'clase2.html', 'clase-3': 'clase3.html', home: 'index.html' };
  let sections = [];
  let currentSection = 0;
  function refreshActiveSections() { sections = Array.from(document.querySelectorAll('section[data-section]')); currentSection = Math.min(currentSection, Math.max(sections.length - 1, 0)); }
  function updateSectionIndicator() { const indicator = document.getElementById('section-indicator'); const prev = document.getElementById('btn-prev'); const next = document.getElementById('btn-next'); if (!indicator || !prev || !next) return; const total = sections.length || 1; indicator.textContent = (currentSection + 1) + ' / ' + total; prev.disabled = currentSection === 0; next.disabled = currentSection >= total - 1; }
  function goToSection(index) { if (!sections.length) refreshActiveSections(); if (index < 0 || index >= sections.length) return; currentSection = index; sections[index].scrollIntoView({ behavior: 'smooth' }); sections[index].classList.add('visible'); updateSectionIndicator(); }
  function updateProgressBar() { const bar = document.getElementById('progress-bar'); if (!bar) return; const docHeight = document.documentElement.scrollHeight - window.innerHeight; const progress = docHeight > 0 ? (window.scrollY / docHeight) * 100 : 0; bar.style.width = progress + '%'; }
  function trackCurrentSection() { if (!sections.length) return; const scrollPos = window.scrollY + window.innerHeight / 3; sections.forEach((section, index) => { const top = section.offsetTop; const bottom = top + section.offsetHeight; if (scrollPos >= top && scrollPos < bottom && currentSection !== index) { currentSection = index; updateSectionIndicator(); } }); }
  function initSectionObserver() { if (!('IntersectionObserver' in window)) { sections.forEach(section => section.classList.add('visible')); return; } const observer = new IntersectionObserver((entries) => { entries.forEach(entry => { if (entry.isIntersecting) entry.target.classList.add('visible'); }); }, { threshold: 0.1 }); sections.forEach(section => observer.observe(section)); }
  function switchLesson(lessonId, sectionIndex = 0) { const current = document.body.dataset.activeLesson; if (current === lessonId && sections.length) { goToSection(sectionIndex); return; } window.location.href = routes[lessonId] || routes.home; }
  function initSidebar() { const sidebarToggle = document.getElementById('sidebar-toggle'); const sidebar = document.getElementById('course-sidebar'); if (!sidebarToggle || !sidebar) return; const stored = localStorage.getItem('sidebarCollapsed'); const mobileDefault = window.matchMedia('(max-width: 768px)').matches; const shouldCollapse = stored === 'true' || (stored === null && mobileDefault); sidebar.classList.toggle('collapsed', shouldCollapse); document.body.classList.toggle('sidebar-collapsed', shouldCollapse); sidebarToggle.textContent = shouldCollapse ? '☰' : '✕'; sidebarToggle.addEventListener('click', () => { const isCollapsed = sidebar.classList.toggle('collapsed'); document.body.classList.toggle('sidebar-collapsed', isCollapsed); localStorage.setItem('sidebarCollapsed', String(isCollapsed)); sidebarToggle.textContent = isCollapsed ? '☰' : '✕'; }); document.querySelectorAll('.lesson-tab[data-lesson]').forEach(tab => { tab.addEventListener('click', (event) => { const lessonId = tab.dataset.lesson; if (document.body.dataset.activeLesson === lessonId) { event.preventDefault(); goToSection(0); } }); }); document.querySelectorAll('[data-switch-lesson]').forEach(btn => { btn.addEventListener('click', () => switchLesson(btn.dataset.switchLesson)); }); document.querySelectorAll('[data-home-link]').forEach(btn => { btn.addEventListener('click', () => { window.location.href = btn.dataset.homeLink || 'index.html'; }); }); }
  function initPresentationNav() { const prev = document.getElementById('btn-prev'); const next = document.getElementById('btn-next'); if (prev) prev.addEventListener('click', () => goToSection(currentSection - 1)); if (next) next.addEventListener('click', () => goToSection(currentSection + 1)); document.addEventListener('keydown', (e) => { if (!sections.length || ['INPUT', 'TEXTAREA', 'SELECT'].includes(document.activeElement?.tagName)) return; if ((e.key === 'ArrowRight' || e.key === 'ArrowDown') && currentSection < sections.length - 1) { e.preventDefault(); goToSection(currentSection + 1); } else if ((e.key === 'ArrowLeft' || e.key === 'ArrowUp') && currentSection > 0) { e.preventDefault(); goToSection(currentSection - 1); } }); }
  function initAgendaAccordions(scope = document) { scope.querySelectorAll('.agenda-item').forEach(item => { item.addEventListener('click', () => { const parent = item.closest('.agenda-timeline') || document; const isActive = item.classList.contains('active'); parent.querySelectorAll('.agenda-item').forEach(i => i.classList.remove('active')); if (!isActive) item.classList.add('active'); }); }); }
  function init() { refreshActiveSections(); initSidebar(); initPresentationNav(); initSectionObserver(); initAgendaAccordions(); updateSectionIndicator(); updateProgressBar(); if (sections[0]) sections[0].classList.add('visible'); window.addEventListener('scroll', () => { updateProgressBar(); trackCurrentSection(); }); }
  window.Course = { goToSection, switchLesson, refreshActiveSections, updateProgressBar, trackCurrentSection, updateSectionIndicator, initAgendaAccordions };
  document.addEventListener('DOMContentLoaded', init);
})();
